
[env]
term = "xterm-256color"

# [colors.primary]
# background = "#000000"

[font]
size = 16

[font.normal]
family = "iMWritingMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1

[window.padding]
x = 12
y = 12

# Normal colors
[colors.normal]
black = '#282828'
red = '#ee5396'
green = '#25be6a'
yellow = '#08bdba'
blue = '#78a9ff'
magenta = '#be95ff'
cyan = '#33b1ff'
white = '#dfdfe0'

# Bright colors
[colors.bright]
black = '#484848'
red = '#f16da6'
green = '#46c880'
yellow = '#2dc7c4'
blue = '#8cb6ff'
magenta = '#c8a5ff'
cyan = '#52bdff'
white = '#e4e4e5'

[general]
live_config_reload = true
